- fail: msg="Tomcat on RHEL7 only"
  when: os != "rhel7"
- name: Make sure ZIP utilities exists on the box
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - zip
    - unzip
- name: install java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64
  yum: name=java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64
- name: create tomcat8 account with proper UID
  user: name=tomcat8 uid=1010 password=$ENCRYPTED$PASSWORD createhome=yes home=/home/tomcat8
- name: Make tomcat8 dir
  file: path=/usr/share/tomcat8 state=directory owner=tomcat8 group=tomcat8
- name: Make tomcat8 ssh dir
  file: path=/home/tomcat8/.ssh state=directory owner=tomcat8
- name: toggle off java updates
  lineinfile: path=/etc/yum.conf insertbefore="^installonly_limit" line="exclude=java*"
- name: reset zeus stuff for ASE deployment tooling
  lineinfile: path=/etc/sudoers insertbefore="^ansible" line="zeus ALL=(ALL) ALL"
- name: allow tomcat8 user to restart splunk
  lineinfile: path=/etc/sudoers insertbefore="^ansible" line="tomcat8 ALL=(ALL) NOPASSWD{{":"}} /opt/splunkforwarder/bin/splunk restart"
- name: add ssh authorized keys for DTS
  authorized_key:
    user: tomcat8
    state: present
    key: '{{ item }}'
    exclusive: True
  with_file: 
    - static_files/jenkins_ssh_key_dts
    - static_files/jenkins_tomcat8_key_dts
  when:  sat6env != "prod"
- name: add ssh authorized keys for Prod
  authorized_key:
    user: tomcat8
    state: present
    key: '{{ item }}'
    exclusive: True
  with_file: 
    - static_files/jenkins_ssh_key_prod
    - static_files/jenkins_tomcat8_key_prod
  when:  sat6env == "prod"
- name: set sigpending for tomcat8 user
  pam_limits: domain=tomcat8 limit_type='-' limit_item=sigpending value=192002
- name: set nproc for tomcat8 user
  pam_limits: domain=tomcat8 limit_type='-' limit_item=nproc value=16384
- name: set stack for tomcat8 user
  pam_limits: domain=tomcat8 limit_type='-' limit_item=stack value=10240
- name: set nofile for tomcat8 user
  pam_limits: domain=tomcat8 limit_type='-' limit_item=nofile value=65536 
- name: remove 90-nproc.conf
  file:
    path: /etc/security/limits.d/90-nproc.conf
    state: absent
- name: Create Ansible Directory
  file: 
    path: /etc/ansible/facts.d
    state: directory 
    owner: ansible
    mode: 755